# SPDX-FileCopyrightText: 2025 Nitesh Kumar Debnath <nitkdnath@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

[default.extend-identifiers]
facter = "facter"
browseable = "browseable"
ede = "ede"
substituters = "substituters"
