[[language]]
auto-format = true
name = "nix"
language-servers = ["nixd", "nil"]

[language.formatter]
command = "nixfmt"

[[language]]
auto-format = true
name = "yaml"

[language.formatter]
args = ["fmt", "--stdin", "yaml"]
command = "dprint"

[[language]]
auto-format = true
name = "yuck"

[language.formatter]
command = "parinfer-rust"

[[language]]
language-servers = ["just-lsp"]
name = "just"

[language-server.just-lsp]
command = "just-lsp"

[language-server.nixd.config.nixd.options]
nixos.expr = "(builtins.getFlake \"/home/ssmvabaa/nixos-machine\").nixosConfigurations.tjmaxxer.options"
home-manager.expr = "(builtins.getFlake \"/home/ssmvabaa/nixos-machine\").currentSystem.legacyPackages.homeConfigurations.ssmvabaa.options"
flake-parts.expr = "(builtins.getFlake \"/home/ssmvabaa/nixos-machine\").debug.options"
flake-parts2.expr = "(builtins.getFlake \"/home/ssmvabaa/nixos-machine\").currentSystem.options"

[language-server.yaml-language-server.config.yaml]
validation = true
[language-server.yaml-language-server.config.yaml.format]
enable = true

[language-server.tinymist]
command = "tinymist"
[language-server.tinymist.config]
formatterMode = "typstyle"
preview.background.enabled = true
preview.background.args = [
  "--data-plane-host=127.0.0.1:23635",
  "--invert-colors=never",
  "--open",
]
