# SPDX-FileCopyrightText: 2025 Nitesh Kumar Debnath <nitkdnath@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

[[language]]
auto-format = true
name = "nix"

[[language]]
auto-format = true
name = "yaml"

[language-server.nixd.config.nixd.options]
nixos.expr = "(builtins.getFlake \"/home/ssmvabaa/nixos-machine\").nixosConfigurations.tjmaxxer.options"
home-manager.expr = "(builtins.getFlake \"/home/ssmvabaa/nixos-machine\").nixosConfigurations.tjmaxxer.options.home-manager.users.type.getSubOptions []"
flake-parts.expr = "(builtins.getFlake \"/home/ssmvabaa/nixos-machine\").debug.options"
flake-parts-perSystem.expr = "(builtins.getFlake \"/home/ssmvabaa/nixos-machine\").currentSystem.options"

[language-server.yaml-language-server.config.yaml]
validation = true
[language-server.yaml-language-server.config.yaml.format]
enable = true

[language-server.tinymist]
command = "tinymist"
[language-server.tinymist.config]
formatterMode = "typstyle"
preview.background.enabled = true
preview.background.args = [
  "--data-plane-host=127.0.0.1:23635",
  "--invert-colors=never",
  "--open",
]
