# SPDX-FileCopyrightText: 2025 Nitesh Kumar Debnath <nitkdnath@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
name: "Test machines"
on:
  # push:
  workflow_call:
jobs:
  tests:
    name: "Build machines"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    strategy:
      matrix:
        machine: [tjmaxxer, disko-elysium, msi-colgate]
    steps:
      - name: Maximize Runner Space
        uses: justinthelaw/maximize-github-runner-space@master
        with:
          remove-android: "true"
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: actions/checkout@v6
        with:
          # NOTE: Needs token for running actions
          token: ${{ steps.generate-token.outputs.token }}
          persist-credentials: false
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ steps.generate-token.outputs.token }}
      - uses: cachix/cachix-action@3ba601ff5bbb07c7220846facfa2cd81eeee15a1
        with:
          name: machines
          # If you chose signing key for write access
          # signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
          # If you chose API tokens for write access OR if you have a private cache
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build ${{ matrix.machine }}
        run: |
          cachix use nix-community
          nix build  --max-jobs 4 --cores 0 --print-build-logs --keep-going \
          --eval-profiler flamegraph \
          .#nixosConfigurations.${{ matrix.machine }}.config.system.build.toplevel
          nix shell nixpkgs#inferno -c \
          inferno-flamegraph nix.profile > ${{ matrix.machine }}-build.svg
      - uses: actions/upload-artifact@v6
        id: eval-artifact
        with:
          name: ${{ matrix.machine }} eval profile
          path: ${{ matrix.machine }}-build.svg
      - name: Add PR Comment
        uses: mshick/add-pr-comment@v2.8.2
        with:
          message-id: ${{ matrix.machine }} eval profile
          message: "${{ matrix.machine }} eval profile: ${{ steps.eval-artifact.outputs.artifact-url }}"
