# SPDX-FileCopyrightText: 2025 Nitesh Kumar Debnath <nitkdnath@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
name: "Test packages"
on:
  # push:
  workflow_call:
jobs:
  tests:
    name: "Build packages"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - .#bizhub-225i
          - .#epson-l3212
          - .#naps2-wrapped
          - .#niri-wrapped
          - .#paperless-ngx-cached
          - .#quickshell-cached
          - .#devShells.x86_64-linux.default
          - .#homeConfigurations.ssmvabaa.activationPackage
    steps:
      - uses: actions/checkout@v6
      - uses: nixbuild/nix-quick-install-action@v34
        with:
          nix_conf: |
            keep-env-derivations = true
            keep-outputs = true
      - uses: nix-community/cache-nix-action@d81037ab7edbb4443c3ee77c734acdaf66ecc32d
        with:
          # restore and save a cache using this key
          primary-key: nix-${{ runner.os }}-package-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          # primary-key: nix-${{ runner.os }}-package-${{ matrix.package }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          # if there's no cache hit, restore a cache by this prefix
          restore-prefixes-first-match: |
            nix-${{ runner.os }}-package-${{ matrix.package }}
            nix-${{ runner.os }}-package
            nix-${{ runner.os }}-
          # collect garbage until the Nix store size (in bytes) is at most this number
          # before trying to save a new cache
          # 1G = 1073741824
          gc-max-store-size-linux: 1G
          # do purge caches
          purge: true
          # purge all versions of the cache
          purge-prefixes: nix-${{ runner.os }}-package
          # created more than this number of seconds ago
          purge-created: 0
          # or, last accessed more than this number of seconds ago
          # relative to the start of the `Post Restore and save Nix store` phase
          purge-last-accessed: 0
          # except any version with the key that is the same as the `primary-key`
          purge-primary-key: never
      - uses: cachix/cachix-action@29121a2db12c7ff8b89724a8898ca20d33bb4ea3
        with:
          name: machines
          # If you chose signing key for write access
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
          # If you chose API tokens for write access OR if you have a private cache
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build ${{ matrix.package }}
        run: |
          nix build --max-jobs 4 --cores 0 \
          ${{ matrix.package }}
