# SPDX-FileCopyrightText: 2025 Nitesh Kumar Debnath <nitkdnath@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
name: "Test packages"
on:
  # push:
  workflow_call:
jobs:
  tests:
    name: "Build packages"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - .#bizhub-225i
          - .#epson-l3212
          - .#naps2-wrapped
          - .#devShells.x86_64-linux.default
    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: actions/checkout@v6
        with:
          # NOTE: Needs token for running actions
          token: ${{ steps.generate-token.outputs.token }}
          persist-credentials: false
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ steps.generate-token.outputs.token }}
      - uses: cachix/cachix-action@3ba601ff5bbb07c7220846facfa2cd81eeee15a1
        with:
          name: machines
          # If you chose signing key for write access
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
          # If you chose API tokens for write access OR if you have a private cache
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build ${{ matrix.package }}
        run: |
          nix build --max-jobs 4 --cores 0 --print-build-logs \
          ${{ matrix.package }}
