# SPDX-FileCopyrightText: 2025 Nitesh Kumar Debnath <nitkdnath@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
name: "Test machines"
on:
  # push:
  workflow_call:
jobs:
  tests:
    name: "Build machines"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        machine: [tjmaxxer, disko-elysium, msi-colgate, vps01]
    steps:
      - uses: actions/checkout@v6
      - uses: wimpysworld/nothing-but-nix@main
        with:
          hatchet-protocol: "rampage" # Options: holster, carve, cleave (default), rampage
          nix-permission-edict: true
      - uses: nixbuild/nix-quick-install-action@v34
        with:
          nix_conf: |
            keep-env-derivations = true
            keep-outputs = true
      - name: Cache flake metadata
        uses: actions/cache@v5
        with:
          path: |
            ~/.cache/nix
            ~root/.cache/nix
          key: nix-${{ runner.os }}-machine-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          # key: nix-${{ runner.os }}-machine-${{ matrix.machine }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-keys: |
            nix-${{ runner.os }}-machine-${{ matrix.machine }}
            nix-${{ runner.os }}-
      - uses: cachix/cachix-action@29121a2db12c7ff8b89724a8898ca20d33bb4ea3
        with:
          name: machines
          # If you chose signing key for write access
          # signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
          # If you chose API tokens for write access OR if you have a private cache
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build ${{ matrix.machine }}
        run: |
          nix build  --max-jobs 4 --cores 0 --print-build-logs \
          .#nixosConfigurations.${{ matrix.machine }}.config.system.build.toplevel
