name: "Test machines"
on:
  # push:
  workflow_call:
jobs:
  tests:
    name: "Build machines"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        machine: [tjmaxxer, disko-elysium, msi-colgate, vps01]
    steps:
      - uses: actions/checkout@v6
      - uses: wimpysworld/nothing-but-nix@10c936d9e46521bf923f75458e0cbd4fa309300d
        with:
          nix-permission-edict: true # Default: false
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v16
        with:
          name: machines
          # If you chose signing key for write access
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
          # If you chose API tokens for write access OR if you have a private cache
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Get narHash
        id: get-narHash
        run: echo "narHash=$(nix flake metadata --json | jq .locked.narHash)" >> $GITHUB_OUTPUT
      - name: Cache flake metadata
        uses: actions/cache@v4
        with:
          path: ~/.cache/nix
          key: eval-cache-${{ matrix.machine }}-${{ steps.get-narHash.outputs.narHash }}
          restore-keys: |
            eval-cache-${{ matrix.machine }}
            eval-cache-
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build ${{ matrix.machine }}
        run: |
          cachix use niri
          nix build --option max-jobs 4 \
           .#nixosConfigurations.${{ matrix.machine }}.config.system.build.toplevel
