name: "Flake check"
on:
  workflow_call:
jobs:
  flake-check:
    name: "Run flake checks"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix flake check --accept-flake-config
